dataset:
  dataroot: "/data/datasets/ground_texture/mini"
  camera_config: "/data/datasets/ground_texture/mini/camera.yaml"

correlation_flow:
  width: 448
  height: 448
  sigma: 0.2 # For Gaussian Kernel
  lambda: 0.1 # For regularization
