dataset:
  dataroot: "/media/xukuan/0000678400004823/dataset/ground_texture/uniform/1220"
  camera_config: "/media/xukuan/0000678400004823/dataset/ground_texture/uniform/1220/camera.yaml"

correlation_flow:
  width: 448
  height: 448
  sigma: 0.2 # For Gaussian Kernel
  lambda: 0.1 # For regularization
